# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

do_as_bifrost_install = false

ansible_install_root=(ENV['ANSIBLE_INSTALL_ROOT'] || "/opt/stack")
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  ## ssh config default setup
  config.ssh.forward_agent    = true
  config.ssh.insert_key       = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]
  config.ssh.forward_x11      = true

  ## config.vm.box = 'ubuntu/trusty64'
  #### config.vm.box = 'ubuntu/trusty64'
  ## config.vm.box = "generic/centos7"
  ## config.vm.box_version = "1.8.60"
  ## config.vm.box_version = "1809.01"
  ## https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1805_01.VirtualBox.box
  config.vm.box_url = "https://coha.tw/pub/bifrost-ce75-dev.json"
  config.vm.box = "ce75-dev"


  config.vm.define 'bifrost' do |bifrost|
    bifrost.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '8196', '--cpus', '4']
      # the setting below are to improve performance on mac's and should have little impact elsewhere.
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
      vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
      vb.customize ["modifyvm", :id, "--nictype3", "Am79C973"]
    end

    # If ANSIBLE_INSTALL_ROOT is available, set that value inside the VM
    if ENV['ANSIBLE_INSTALL_ROOT']
      bifrost.vm.provision "shell", inline: <<-SHELL
        echo "export ANSIBLE_INSTALL_ROOT=#{ENV['ANSIBLE_INSTALL_ROOT']}" >> /etc/profile.d/ansible-root.sh
      SHELL
    end

    # Set up private NAT'd network <<== eth1
    bifrost.vm.network 'private_network', ip: '192.168.99.10' # it goes to 11
    ## ==========================================================================
    # This assumes you have DHCP on your bridged network. if not you will need
    # to statically configure to allow  Bifrost to manage hardware attached to
    # the bridged interface.
    # NOTE(TheJulia): Is there a way to abstract the bridged networking...
    # NOTE(NobodyCam): until the above is  done this needs to be set to a valid interface

    # Set up public_network <<== eth2
    ##### bifrost.vm.network 'public_network', bridge: ''
    ## bifrost.vm.network 'public_network', bridge: 'en0:'
    ## bifrost.vm.network 'public_network', bridge: 'en0: Wi-Fi (Wireless)'
    bifrost.vm.network 'private_network', ip: '192.168.203.10' # it goes to 11

    # besure we get the entire bifrost directory tree
    ## bifrost.vm.synced_folder "../../.", "/home/vagrant/bifrost", type: "rsync"
    ## bifrost.vm.synced_folder "../../.", "/vagrant", type: "virtualbox"
    bifrost.vm.synced_folder "../../.", "/home/vagrant/bifrost", type: "virtualbox"
    ## nfs ## bifrost.vm.synced_folder "../../.", "/home/vagrant/bifrost", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc', 'actimeo=2']
    ## bifrost.vm.synced_folder "../../.", "/home/vagrant/bifrost", type: "sshfs"
    ## bifrost.vm.synced_folder "../../.", "/home/vagrant/bifrost", type: "smb", smb_username: "usr0101039", smb_password: "fc999Bem"
    ## bifrost.vm.synced_folder "../../.", "/home/vagrant/bifrost", type: "smb", mount_options: ['username=usr0101039', 'password=fc999Bem']
    ##### default work dir synced_folder
    bifrost.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    ## nfs ## bifrost.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc', 'actimeo=2']
    ## bifrost.vm.synced_folder ".", "/vagrant", type: "sshfs"
    ## bifrost.vm.synced_folder ".", "/vagrant", type: "smb", smb_username: "usr0101039", smb_password: "fc999Bem"
    ## bifrost.vm.synced_folder ".", "/vagrant", type: "smb", mount_options: ['username=usr0101039', 'password=fc999Bem']

    ## addedd GMO baremetal
    bifrost.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa_2"
    bifrost.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
    bifrost.vm.provision "shell" do |s|
      ssh_prv_key = ''
      ssh_pub_key = ''
      if File.file?("#{Dir.home}/.ssh/id_rsa")
        ssh_prv_key = File.read("#{Dir.home}/.ssh/id_rsa")
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      else
        puts "No SSH key found. You will need to remedy this before pushing to the repository."
      end
      s.inline = <<-SHELL
        hostname;
        ls -lv ~/.ssh/;
        if grep -sq "#{ssh_pub_key}" /home/vagrant/.ssh/authorized_keys; then
          echo "SSH keys already provisioned."
          exit 0;
        fi
	echo "gui env. installing."
        yum -y install neovim tmux rpm-build-libs.x86_64 rpm-build.x86_64
	## yum -y groupinstall "Server with GUI"
        ## yum -y install virt-manager.noarch neovim epel-release
	##
	##yum -y install \
        ##      ansible \
        ##      ansible-doc.noarch \
        ##      ansible-inventory-grapher.noarch \
        ##      ansible-openstack-modules.noarch \
        ##      ansible-review.noarch \
        ##      ansible-lint.noarch \
        ##      centos-release-openstack-rocky.noarch
	##
        echo "SSH key provisioning."
        mkdir -p /home/vagrant/.ssh/
        touch /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} > /home/vagrant/.ssh/id_rsa.pub
        chmod 644 /home/vagrant/.ssh/id_rsa.pub
        echo "#{ssh_prv_key}" > /home/vagrant/.ssh/id_rsa
        chmod 600 /home/vagrant/.ssh/id_rsa
        sudo chown -R vagrant:vagrant /home/vagrant
	## root
        if grep -sq "#{ssh_pub_key}" /root/.ssh/authorized_keys; then
          echo "SSH keys already provisioned."
          exit 0;
        fi
	##
        echo "SSH key provisioning."
        mkdir -p /root/.ssh/
        touch /root/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        echo #{ssh_pub_key} > /root/.ssh/id_rsa.pub
        chmod 644 /root/.ssh/id_rsa.pub
        echo "#{ssh_prv_key}" > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        exit 0
      SHELL
    end

    bifrost.vm.provision 'ansible_local' do |ansible|
      ## added for 'ansible_local'
      ansible.version = '2.7.8'
      ansible.install_mode = 'pip'
      ## 
      ## ansible.verbose = 'vvv'
      ansible.verbose = 'vv'
      ansible.playbook = 'vagrant_pre.yml'
      ansible.extra_vars = {
          # set key file name here
          ansible_install_root: ansible_install_root,
          public_key: 'id_rsa.pub',
          # Edit the network_interface to match your needs:
          #  eth0 - connected to a Nat network
          #  eth1 - connected to Host-only network named: 'vboxnet1'
          #  eth2 - bridged - Interface must also be set above
          ######## network_interface: 'eth2'
          ############# network_interface: 'eth1'
          network_interface: 'eth2'
      }
    end
    ##
    ##     - name: Install Bifrost
    ##       command: ansible-playbook -vvv -i inventory/target install.yaml -e network_interface={{network_interface}} -e extra_dib_elements=devuser -e ipa_upstream_release=stable-queens -e dib_os_release=xenial -e dib_os_element=ubuntu-minimal
    ##       environment:
    ##           PATH: "{{ansible_env.HOME}}/.local/bin:{{ansible_env.PATH}}"
    ##       args:
    ##           chdir: /home/vagrant/bifrost/playbooks
    if do_as_bifrost_install
      bifrost.vm.provision 'ansible_local' do |ansible|
        ## added for 'ansible_local'
        ansible.version = '2.7.8'
        ansible.install_mode = 'pip'
        ## 
        ## ansible.verbose = 'vvv'
        ansible.verbose = 'vvv'
        ansible.provisioning_path = '/home/vagrant/bifrost/playbooks'
        ansible.inventory_path    = '/home/vagrant/bifrost/playbooks/inventory/target'
        ansible.playbook = 'install.yaml'
        ansible.extra_vars = {
            # set key file name here
            ansible_install_root: ansible_install_root,
            public_key: 'id_rsa.pub',
            ############# network_interface: 'eth1'
            network_interface: 'eth2',
            ## additional option (gmo)
            extra_dib_elements: 'devuser',
            create_image_via_dib: 'true',
            transform_boot_image: 'false',
            ipa_upstream_release: 'stable-queens',
            dib_os_release: 'xenial',
            dib_os_element: 'ubuntu-minimal',
            staging_drivers_include: 'true'
        }
      end
    end
  end
end
